// registry와 분리해 관리하는 앱별 고유 역할·마케팅 문구·대표 지표다.
export const appCopy = [
  {
    id: "outbom",
    prefix: "야외",
    tagline: "바깥바람이 좋은 때",
    description: "지금 나가도 되는지와 가장 좋은 시간, 비·바람·공기·준비물을 알려주는 앱",
    metadataTitle: "야외봄 | 지금 나가도 되는지와 좋은 시간",
    metadataDescription: "걷기·러닝·등산·자전거에 지금 나가도 되는지와 비·바람·대기질, 활동별 준비물을 오늘과 내일 예보로 확인하세요.",
    mobileValue: "지금 출발해도 되는지",
    mobileAction: "판단 보기",
    tone: "out",
    eyebrow: "지금, 나가도 될까?",
    heroTitle: "출발 판단을 가장 먼저 봅니다.",
    heroBody: "비와 바람, 체감온도와 공기를 함께 살펴 지금 출발해도 되는지와 더 나은 시간을 한 번에 알려드립니다.",
    metrics: [
      { value: "지금", label: "출발 판단" },
      { value: "시간별", label: "좋은 때" },
      { value: "활동별", label: "준비물" },
    ],
    highlights: ["지금 출발 판단", "비·바람·공기", "활동별 준비물"],
  },
  {
    id: "homebom",
    prefix: "청약",
    tagline: "다시 오지 않을 그 하루",
    description: "공식 청약 공고의 접수·발표·계약 일정과 다음 행동을 챙기는 앱",
    metadataTitle: "청약봄 | 특별공급·1순위·무순위 청약 일정",
    metadataDescription: "특별공급·1순위·2순위·무순위·재공급의 접수와 발표·계약 일정, 다음 행동을 알림으로 확인하세요.",
    mobileValue: "다음 접수와 발표 일정",
    mobileAction: "일정 보기",
    tone: "home",
    eyebrow: "곧, 문이 열립니다",
    heroTitle: "접수 시작과 마감을 놓치지 않게.",
    heroBody: "공식 공고를 한자리에 모아 두고, 마음에 둔 청약의 접수와 발표·계약에서 지금 할 일을 먼저 보여드립니다.",
    metrics: [
      { value: "공식", label: "공고 출처" },
      { value: "접수", label: "다음 행동" },
      { value: "발표·계약", label: "후속 일정" },
    ],
    highlights: ["공식 청약 공고", "접수·발표·계약", "관심 공고 알림"],
  },
  {
    id: "runningbom",
    prefix: "러닝",
    tagline: "다시 출발선에 서는 날",
    description: "전국 러닝 대회를 빠르게 찾고 접수 시작·마감과 대회일을 챙기는 앱",
    metadataTitle: "러닝봄 | 마라톤 대회 접수 일정과 알림",
    metadataDescription: "전국 마라톤·러닝 대회를 지역과 거리로 찾고, 공식 접수 일정과 시작 알림을 확인하세요.",
    mobileValue: "곧 열리는 대회 접수",
    mobileAction: "대회 찾기",
    tone: "run",
    eyebrow: "저 앞, 다가오는 출발선",
    heroTitle: "대회와 접수 상태를 빠르게 찾습니다.",
    heroBody: "지역과 거리, 접수 상태로 전국 대회를 좁히고 접수 시작·마감과 대회일을 헷갈리지 않게 구분합니다.",
    metrics: [
      { value: "전국", label: "대회 탐색" },
      { value: "지역·거리", label: "빠른 필터" },
      { value: "접수", label: "시작 알림" },
    ],
    highlights: ["빠른 대회 검색", "지역·거리·상태", "공식 접수처"],
  },
  {
    id: "certbom",
    prefix: "자격증",
    tagline: "시험 준비가 제때 닿도록",
    description: "공식 시험을 찾고 접수부터 시험일까지 일정과 준비물을 챙기는 앱",
    metadataTitle: "자격증봄 | 자격증 시험 일정·준비물·추천",
    metadataDescription: "공식 출처의 자격증 시험과 2026 일정을 확인하고, 현재 접수 중인 시험과 내게 맞는 추천을 받아보세요.",
    mobileValue: "현재 접수와 시험 일정",
    mobileAction: "시험 찾기",
    tone: "cert",
    eyebrow: "접수부터 시험일까지, 놓치지 않게",
    heroTitle: "지금 접수할 시험과 다음 행동을 봅니다.",
    heroBody: "공식 출처의 시험을 모아 현재 접수와 다음 회차를 먼저 보여주고, 시험 일정·준비물·공식 접수처를 연결합니다.",
    metrics: [
      { value: "97개", label: "시험 catalog" },
      { value: "현재 접수", label: "우선 표시" },
      { value: "공식", label: "출처 연결" },
    ],
    highlights: ["현재 접수 우선", "3+7 맞춤 추천", "공식 일정·준비물"],
  },
] as const;
