// DO NOT EDIT. ops/registry/apps.yml에서 생성된 홈페이지 앱 메타데이터다.
export const generatedAppMeta = [
  {
    "id": "outbom",
    "name": "야외봄",
    "englishName": "OutBom",
    "repo": "robom-labs/outbom",
    "version": "0.25.6",
    "dataVersion": "runtime-weather-v1",
    "webUrl": "https://robom-labs.github.io/outbom/",
    "healthcheckUrl": "https://robom-labs.github.io/outbom/",
    "deployProvider": "github-pages",
    "basePath": "/outbom/",
    "privacyUrl": "https://robom.kr/privacy/outbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.outbom",
    "iosBundleId": "kr.robom.outbom",
    "googlePlayUrl": "",
    "googlePlayStatus": "internal",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/outbom/",
    "stableInstallUrl": "https://robom.kr/get/outbom",
    "mobileStatus": "native-closed-test-active",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-07-24T16:55:00+09:00",
    "lastDeployedSha": "3cf078e8f77e3ce2e5ac71be72fe1c104eb996fe",
    "lastDataSyncAt": "2026-07-16T13:42:23+09:00",
    "freshnessStatus": "runtime"
  },
  {
    "id": "homebom",
    "name": "청약봄",
    "englishName": "HomeBom",
    "repo": "robom-labs/homebom",
    "version": "0.14.8",
    "dataVersion": "official-notices-runtime-v1",
    "webUrl": "https://robom-labs.github.io/homebom/",
    "healthcheckUrl": "https://robom-labs.github.io/homebom/",
    "deployProvider": "github-pages",
    "basePath": "/homebom/",
    "privacyUrl": "https://robom.kr/privacy/homebom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.homebom",
    "iosBundleId": "kr.robom.homebom",
    "googlePlayUrl": "",
    "googlePlayStatus": "internal",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/homebom/",
    "stableInstallUrl": "https://robom.kr/get/homebom",
    "mobileStatus": "native-closed-test-review",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-07-24T16:24:00+09:00",
    "lastDeployedSha": "0233c5beb96d84780b0e1ffe438c6a13469d9845",
    "lastDataSyncAt": "2026-07-17T21:05:01+09:00",
    "freshnessStatus": "runtime"
  },
  {
    "id": "runningbom",
    "name": "러닝봄",
    "englishName": "RunningBom",
    "repo": "robom-labs/runningbom",
    "version": "0.18.3",
    "dataVersion": "2026.07.24-race-data-12",
    "webUrl": "https://robom-labs.github.io/runningbom/",
    "healthcheckUrl": "https://robom-labs.github.io/runningbom/",
    "deployProvider": "github-pages",
    "basePath": "/runningbom/",
    "privacyUrl": "https://robom.kr/privacy/runningbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.runningbom",
    "iosBundleId": "kr.robom.runningbom",
    "googlePlayUrl": "",
    "googlePlayStatus": "internal",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/runningbom/",
    "stableInstallUrl": "https://robom.kr/get/runningbom",
    "mobileStatus": "native-closed-test-active",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-07-24T14:19:53+09:00",
    "lastDeployedSha": "a8e05b10220237a0ac7464d755b519c565794791",
    "lastDataSyncAt": "2026-07-24T08:48:14+09:00",
    "freshnessStatus": "healthy"
  },
  {
    "id": "certbom",
    "name": "자격증봄",
    "englishName": "CertBom",
    "repo": "robom-labs/certbom",
    "version": "0.8.3",
    "dataVersion": "2026.07.24-v4",
    "webUrl": "https://certbom.vercel.app/",
    "healthcheckUrl": "https://certbom.vercel.app/",
    "deployProvider": "vercel",
    "basePath": "/",
    "privacyUrl": "https://robom.kr/privacy/certbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.certbom",
    "iosBundleId": "kr.robom.certbom",
    "googlePlayUrl": "",
    "googlePlayStatus": "internal",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://certbom.vercel.app/",
    "stableInstallUrl": "https://robom.kr/get/certbom",
    "mobileStatus": "native-closed-test-active",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-07-24T14:30:00+09:00",
    "lastDeployedSha": "6f2aa946a79681fdd47f5d52f464c184f3b48d0a",
    "lastDataSyncAt": "2026-07-24T14:30:00+09:00",
    "freshnessStatus": "last-known-good"
  }
] as const;
